### ISSUE TITLE
[BUG]: Thrill Drive 3 Not Registering Input for Analog Controls

### ISSUE THREAD

**Issue by CommanderJansen** [987123879113/pcsx2#3]
### Describe the Bug

Thrill Drive 3 is not receiving any steering, brake, or accelerator input. In-game, the wheel remains fully turned to the right, and neither the accelerator or brake move from 0.

![image](https://user-images.githubusercontent.com/8525150/160294584-90b710d0-3b8c-4103-bc5a-2c80149c6a95.png)

Attempting to calibrate always throws an error.

![image](https://user-images.githubusercontent.com/8525150/160294826-3c1a41e6-cefb-450e-938f-9aa4766c4d39.png)

The game will also constantly spam "err -1" in the console.

Keys for gear up/down and start work just fine, however. Have tried multiple gamepads, joysticks, and keyboard binding combinations, and received the same result.

### Reproduction Steps

Bind analog sticks to ThrillDriveWheelAnalog, ThrillDriveAccelAnalog, ThrillDriveBrakeAnalog (or keys to their non-analog counterparts) using Raw Input in the USB settings.

![image](https://user-images.githubusercontent.com/8525150/160295121-a2356b7b-6a2b-4fce-8881-68b73304998a.png)

### Expected Behavior

Expected either analog sticks or keys to work when bound. Hopefully this isn't just me missing something in the binding process.

### PCSX2 Revision

1.7.0-20220327232121- compiled on Mar 27 2022

### Operating System

Windows 10 (64bit)

**Comment by 987123879113** [comment]
I/O broke in a refactoring PR ~4 months ago it seems. It's fixed again and I was able to play a round. 
https://github.com/987123879113/pcsx2/commit/9a1f513ab353a9921ce178b8e4fcf1153b6d3800

Please note that there will still be a calibration error on boot but you can ignore it (go into test menu and then start game, or disable it from the dipswitches).

To be on the safe side: 
- Make sure `InputType=4` in Python2.ini for the Thrill Drive 3 entry
- Set the dipswitches value to `DipSwitch=0100` if you want to remove the calibration check during boot (removes calibration error)

Let me know if it fixes the issue for you.

**Comment by CommanderJansen** [comment]
Excellent - seems to be working properly now. Thanks for your help and the quick response (not to mention getting this all to work in the first place)!
