### ISSUE TITLE
[Feature Request]: Allow booting python2 games via command line

### ISSUE THREAD

**Issue by qxc86** [987123879113/pcsx2#8]
### Description

PCSX2 should have the ability to boot games from command line, but currently it does not appear to be able to do so for python2 games. 

Current behavior, with a fully functional py2 file that will boot "SN2" from the GUI with no issues:

`pcsx2-qtx64-avx2.exe -fullscreen sn2.py2` This fails with "Failed to initialize CDVD", seems to not know we're booting from hard disk. Maybe we can bypass that check?

`pcsx2-qtx64-avx2.exe -fullscreen -bios sn2.py2` This does not go to the bios but instead begins to load, but just gives a black screen. Per the troubleshooting page this might mean that "OPH Flag Hack" isn't enabled. Per https://wiki.pcsx2.net/index.php/Command-line_support it doesn't seem like we can set game fixes on the Qt version specifically, and I could not find the settings in the OSD. But we press on just in case,

`pcsx2-qtx64-avx2.exe -fullscreen -bios -statefile o.p2s sn2.py2` the state file here is simply one created by booting the machine normally with the gui and dropping a state after turning on event mode. This will eventually hang on a white screen when it attempts to change scenes, and unfortunately that behavior is the same when loading the state in the GUI. This can't be used to work around anything. Functional save states would be a different issue. 

### Reason

Many reasons, but personally I'd just like to be able to hook the game into a frontend program like I do with MAME. It's also a feature of upstream that has been broken... or that I'm not using correctly. :) 

This use case also happens to bypass https://github.com/987123879113/pcsx2/issues/5 by just restarting PCSX2 every launch. For whatever that's worth. 

### Examples

PCSX2 can normally boot games this way, as can other emulators such as MAME.

**Comment by 987123879113** [comment]
The Py2 files are not meant to be launched, they're meant to be imported once and then you launch a game from the PCSX2 game list. What you'd ideally want is a way to launch games from the game list via the command line. If such a thing ever gets added to upstream it'll be merged into this fork, but I have no intention of coding such a feature.
